# Generated by Django 4.2.5 on 2023-10-17 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='cod',
            field=models.CharField(default='00000000000', max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
