# Generated by Django 4.2.3 on 2023-11-14 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0003_alter_estadio_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='cod',
            field=models.CharField(blank=True, default=None, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
