# Generated by Django 4.2.3 on 2023-11-21 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0005_estadio_inauguracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='inauguracao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 9, 55, 53, 917687), help_text='Escolha uma data e hora', verbose_name='Data de Inauguração'),
        ),
    ]
