# Generated by Django 4.2.7 on 2023-11-28 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0009_alter_estadio_options_alter_estadio_inauguracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='inauguracao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 18, 51, 6, 128217), help_text='Escolha uma data e hora', verbose_name='Data de Inauguração'),
        ),
    ]
